language: node_js
node_js:
  - '14.0'
  - '12.0'
  - '10.0'
  - '8.0'
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c27fddacc09aaa988b05
    on_success: change
    on_failure: always
    on_start: never
